config/routes.rb
Rails.application.routes.draw do
  resources :roads
  resources :trips
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/road.rb
class Road < ApplicationRecord
  has_many :trips
  has_many :users, :through => :trips
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :road
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
  has_many :roads, :through => :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to trips_url
    end
  end
end

app/controllers/roads_controller.rb
class RoadsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_action :authenticate_user!

  def new
    @trip = Trip.new
  end

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      flash[:success] = "Success!"
      redirect_to trip_path(@trip)
    else
      flash[:error] = "Error :("
      redirect_to new_trip_path
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit, alert: "Try again"
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path, notice: "Trip deleted"
  end

  private
    def trip_params
      params.require(:trip).permit(:road_id,:date,:time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roads_helper.rb
module RoadsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Road On</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    body{
        background-image: url("https://www.batchbicycles.com/media/wysiwyg/home-slide/batch_ebike_rotator.jpg");
        background-size: cover;
        background-repeat:no-repeat;
    }
  </style>
  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a><strong><%= link_to "Road On", "/trips/", class:"navbar-brand" %></strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a><%= link_to "Create", "/trips/new", class:"btn btn-primary" %></a>
          </li>
        </ul>
      </div>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Edit profile", edit_user_registration_path, class:"dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </li>
        </ul>
    </nav>
    <% else %>
      <nav class="navbar navbar-dark bg-dark">
        <strong><%= link_to "ROAD ON", root_path, class: "navbar-brand"%></strong>
        <div>
          <a><%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary"%></a>
          <a><%= link_to "Login", new_user_session_path, class:"btn btn-primary" %></a>
        </div>
      </nav>
    <% end %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/roads/edit.html.erb
<h1>Roads#edit</h1>
<p>Find me in app/views/roads/edit.html.erb</p>

app/views/roads/index.html.erb
<h1>Roads#index</h1>
<p>Find me in app/views/roads/index.html.erb</p>

app/views/roads/new.html.erb
<h1>Roads#new</h1>
<p>Find me in app/views/roads/new.html.erb</p>

app/views/roads/show.html.erb
<h1>Roads#show</h1>
<p>Find me in app/views/roads/show.html.erb</p>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <select class="form-control" id="exampleFormControlSelect1" name="trip[road_id]">
      <option>Select a road</option>
      <%= options_for_select(Road.all.map{|v| [v.name, v.id]}, selected: @trip.road_id) %>
    </select>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
<br>
  <div class="field">
    <%= form.label :time %>
    <%= form.time_field :time %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Create", class:"btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/trips/_roads.html.erb
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <% Road.all.each_with_index do |v,i| %>
      <li data-target="#carouselExampleCaptions" data-slide-to="<% i+1 %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.unsplash.com/photo-1494783367193-149034c05e8f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80"
        class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>ROADS</h1>
          <br>
          </div>
      </div>
      <% Road.all.each do |v| %>
      <div class="carousel-item">
        <img src="<%= v.image %>" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5><%= v.name %></h5>
          <p><%= v.description %></p>
        </div>
      </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/trips/edit.html.erb
<div class=container>
<div class="row justify-content-md-center">

<div class="col-7">
  <%= render 'roads' %>
</div>

<div class="col-4">
<div class="jumbotron style="background-color: #FBFBFB;"">
<h2 class="text-center">Edit Trip</h2>
<hr>
  <%= render 'form', trip: @trip %>

  <%= link_to 'Back', trips_path %>
</div>

</div>
</div>
</div>

app/views/trips/index.html.erb
<div class="container">
<div class="row">
<% @trips.each do |trip| %>
  <div class="col">
  <div class="card">
  <div class="card-header">
    <% if current_user.email == trip.user.email %>
    <%= "You" %>
    <% else %>
    <%= trip.user.email %>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%=link_to trip.road.name, "/trips/#{trip.id}", class:"btn btn-primary"%></h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
  </div>
  </div>
  <br>
<% end %>
</div>
</div>

app/views/trips/new.html.erb
<div class=container>
<div class="row justify-content-md-center">

<div class="col-7">
  <%= render 'roads' %>
</div>

<div class="col-4">
<div class="jumbotron style="background-color: #FBFBFB;"">
<h2 class="text-center">New Trip</h2>
<hr>
  <%= render 'form', trip: @trip %>
  <%= link_to 'Back', trips_path %>
</div>

</div>
</div>
</div>

app/views/trips/show.html.erb
<div class=container>
<div class="row justify-content-md-center">
<div class="col-4">
<div class="jumbotron style="background-color: #FBFBFB;"">
<p id="notice"><%= notice %></p>

<p>
  <strong>Creator:</strong>
  <%= @trip.user.email %>
</p>

<p>
  <strong>Road:</strong>
  <%= @trip.road.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @trip.date.to_formatted_s(:long_ordinal) %>
</p>

<p>
  <strong>Time:</strong>
  <%= @trip.time.strftime("%H:%M %p") %>
</p>

<% if current_user.email == @trip.user.email %>
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Delete', trips_path, method: :delete %> |
<% else %>
<%= link_to 'Join' %> |
<% end %>
<%= link_to 'Back',trips_path %>
</div>
</div>
</div>
</div>